#!/usr/bin/bash

echo -e "\e[105m>>> Generating static content\e[0m"
NUXT_APP_BASE_URL=/~aellison/ yarn generate
echo -e "\e[105m>>> Syncing static content\e[0m"
rsync -vr --delete -e ssh dist/ aellison@slab1.ethz.ch:/nas/aellison/homepage/

read -p "Open in firefox? " yn
case $yn in
    [Yy]* ) firefox https://n.ethz.ch/~aellison/;;
    *) ;;
esac
